### ISSUE TITLE
How can make spacing between dots ?

### ISSUE THREAD

**Issue by chieuduong-bocasay** [alexvcasillas/react-native-loading-dots#1]
<img width="119" alt="Screen Shot 2020-02-19 at 10 46 19" src="https://user-images.githubusercontent.com/55878972/74800120-16c25d80-5305-11ea-9505-8a5fbf43c656.png">

**Comment by alexvcasillas** [comment]
Hello, sorry for the late response, it's been some crazy months. Dots are set as `space-between` as it's a `flex` layout, so the more `width` you add to the parent, the more the dots will around :)
