### ISSUE TITLE
Compatibility with React Native 0.73?

### ISSUE THREAD

**Issue by airowe** [alexvcasillas/react-native-loading-dots#4]
There is a dependency on this library that is not allowing me to use it. Any chance you could increase this to allow React Native 0.73 users to install?

`peer react-native@"^0.72.5" from react-native-loading-dots@1.4.0`

**Comment by alexvcasillas** [comment]
Hey, sure thing! I didn't have much time lately to keep bumping the RN version :)

**Comment by alexvcasillas** [comment]
Hey @airowe `peerDeps` have been bumped to the latest available! Hope that this works for you 🙇🏻 

```json
"peerDependencies": {
    "react": "^18.2.0",
    "react-native": "^0.73.4"
  }
```

Thank you for using `react-native-loading-dots` 💚

**Comment by airowe** [comment]
Thanks @alexvcasillas! Would it be possible to support typescript as well?

**Comment by alexvcasillas** [comment]
> Thanks @alexvcasillas! Would it be possible to support typescript as well?

Sure, we can add a `.d.ts` file to have types :)

**Comment by airowe** [comment]
> > Thanks @alexvcasillas! Would it be possible to support typescript as well?
> 
> Sure, we can add a `.d.ts` file to have types :)

Thanks @alexvcasillas!

**Comment by alexvcasillas** [comment]
Hey @airowe 👋🏻 Just wanted to let you know that `v1.3.4` now includes a `.d.ts` file with type definitions for this library :)

https://github.com/alexvcasillas/react-native-loading-dots/releases/tag/v1.3.4
