### ISSUE TITLE
React 74

### ISSUE THREAD

**Issue by Lusquinhos** [alexvcasillas/react-native-loading-dots#5]
Hello, can you please update the `peer react-native@"^0.73.4" from react-native-loading-dots@1.3.4` to 0.74?

Thank you!

**Comment by alexvcasillas** [comment]
Sure! I've just updated the `peerDeps` to the latest versions :)

https://www.npmjs.com/package/react-native-loading-dots

**Comment by jbrumwell** [comment]
@alexvcasillas could you update to 0.76? Please and thank you :)

**Comment by alexvcasillas** [comment]
> @alexvcasillas could you update to 0.76? Please and thank you :)

Hey @jbrumwell sorry for the late response! I've been extremely busy lately with work a personal life! I'll upgrade the version this week 😃
